# Indexing | Slicing
- indexing: 특정 위치의 값 선택임
- slicing: 범위 단위의 값 선택임
- fancy indexing: 여러 위치를 한 번에 선택하는 방식임
- boolean indexing: 조건이 `True`인 값만 선택하는 방식임


In [1]:
# numpy import
import numpy as np

## indexing
- 인덱스 번호로 원소 하나를 선택함
- 0번부터 시작함
- 음수 인덱스 사용 가능함


In [2]:
# 1차원 ndarray 인덱싱
arr = np.arange(1,11) #1~10
print("arr:", arr)
print("arr[0], arr[1], arr[2]:", arr[0], arr[1], arr[2])
print("arr[-1], arr[-2], arr[-3]:", arr[-1], arr[-2], arr[-3])

arr: [ 1  2  3  4  5  6  7  8  9 10]
arr[0], arr[1], arr[2]: 1 2 3
arr[-1], arr[-2], arr[-3]: 10 9 8


In [8]:
# 2차원 ndarray 인덱싱
arr2 = arr.reshape(2,5)  #2행 5열 2차원 배열로 변환
print("arr2:", arr2)

print("arr2[0][2]:",arr2[0][2]) #0행의 2번인덱스
print("arr2[1][3]:",arr2[1][3])
print("arr2[-1][4]:",arr2[-1][4]) #음수방향은 0이 아니라 -1부터 시작한다.
print("arr2[-2][-3]:",arr2[-2][-3]) #-2행(역으로 두 번째 행)의 역으로3번인덱스

arr2: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr2[0][2]: 3
arr2[1][3]: 9
arr2[-1][4]: 10
arr2[-2][-3]: 3


## slicing
- `start:stop:step` 형식 사용함
- `start`는 포함함
- `stop`은 포함하지 않음
- `step`은 이동 간격임


In [9]:
# 1차원 배열 슬라이싱
arr1 = np.arange(1,11)
print("arr1: ", arr1) #[1,2,3,4,5,6,7,8,9,10]
print("arr1[2:7]: ", arr1[2:7]) # [3,4,5,6,7] 슬라이싱은 끝번인덱스를 미포함하므로 7번째 인덱스인 8을 포함하지 않음.
print("arr1[2:]: ", arr1[2:])  # [3,4,5,6,7,8,9,10]
print("arr1[:7]: ", arr1[:7])  # [1,2,3,4,5,6,7]
print("arr1[:-1]: ", arr1[:-1]) # [1,2,3,4,5,6,7,8,9] -1번째인 10 미포함
print("arr1[:]: ", arr1[:])  #그대로 배열복사
print("arr1[:-2:2]: ", arr1[:-2:2]) #[1,3,5,7]
print("arr1[::-1]: ", arr1[::-1]) #[10  9  8  7  6  5  4  3  2  1]



arr1:  [ 1  2  3  4  5  6  7  8  9 10]
arr1[2:7]:  [3 4 5 6 7]
arr1[2:]:  [ 3  4  5  6  7  8  9 10]
arr1[:7]:  [1 2 3 4 5 6 7]
arr1[:-1]:  [1 2 3 4 5 6 7 8 9]
arr1[:]:  [ 1  2  3  4  5  6  7  8  9 10]
arr1[:-2:2]:  [1 3 5 7]
arr1[::-1]:  [10  9  8  7  6  5  4  3  2  1]


In [10]:
# 2차원 배열 슬라이싱
arr2 = np.arange(1,13).reshape(3,4)
print("arr2:", arr2)
print("arr2[:, :]:", arr2[:, :]) #행방향 열방향 둘다 슬라이싱 안 함. 그래서 결과 동일.
print("arr2[0, :]:", arr2[0, :]) #0번째행만 슬라이싱 없이 복사됨
print("arr2[:, 0]:", arr2[:, 0]) #모든 행의 0번째 열 값만 보고 싶다. [0].[5],[9]가 아니라 [1,5,9]로 하나의 일차원배열로 다시 만들어짐.
print("arr2[:, 0:2]:", arr2[:, 0:2]) #모든 행의 0번째열 부터 2개 값.[[ 1  2] [ 5  6] [ 9 10]]
print("arr2[1:, 2:]:", arr2[1:, 2:]) #1번째 행의 2번째열 부터 모두. [[7 8] [11 12]]

arr2: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr2[:, :]: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr2[0, :]: [1 2 3 4]
arr2[:, 0]: [1 5 9]
arr2[:, 0:2]: [[ 1  2]
 [ 5  6]
 [ 9 10]]
arr2[1:, 2:]: [[ 7  8]
 [11 12]]


## fancy indexing
- 인덱스 목록으로 여러 원소를 선택함
- 필요한 위치만 골라낼 때 사용함
- 반복문 없이 여러 값을 한 번에 추출 가능함


In [14]:
arr = np.linspace(5,50,10,dtype=int)
print("arr:", arr)
print("arr[[1,2,8]]:", arr[[1,2,8]])

#list 변수를 이용한 인덱싱
indexes = [3,5,7]
print("arr[indexes]:", arr[indexes])

arr: [ 5 10 15 20 25 30 35 40 45 50]
arr[[1,2,8]]: [10 15 45]
arr[indexes]: [20 30 40]


In [26]:
# 2차원 fancy indexing
arr = np.linspace(5,100,20,dtype=int).reshape(4,5)
print(arr)

print("arr[[0]]:\n", arr[0])
print("arr[[0,1]]:\n", arr[[0,1]])  #0번과 1번행 선택.

#arr[[0,2],[1,3]] 코드의 뜻: 행과 열을 나타내는 list에서 같은 인덱스 값을 얻어와 2차원의 좌표를 만들어서 해당 위치 값을 반환.
# --> 0번째 행의 1번 인덱스, 2번째 행의 3번 인덱스  [0][1], [2][3] 이느낌.
print("arr[[0,2],[1,3]]:\n", arr[[0,2],[1,3]]) # [10 70]

print("arr[[0,1],1:4] :\n", arr[[0,1], 1:4])

print("arr[[1, 3], 3:]:\n", arr[[1, 3], 3:])
print("arr[[1, 3], -2:]\n", arr[[1, 3], -2:])

[[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]]
arr[[0]]:
 [ 5 10 15 20 25]
arr[[0,1]]:
 [[ 5 10 15 20 25]
 [30 35 40 45 50]]
arr[[0,2],[1,3]]:
 [10 70]
arr[[0,1],1:4] :
 [[10 15 20]
 [35 40 45]]
arr[[1, 3], 3:]:
 [[ 45  50]
 [ 95 100]]
arr[[1, 3], -2:]
 [[ 45  50]
 [ 95 100]]


### 3차원 배열
- 배열 안에 배열이 중첩된 구조임
- 3차원부터는 공간 그림보다 참조 순서로 이해하는 것이 좋음
- 접근 순서: 바깥 축 → 행 → 열 순서임


In [33]:
lst = [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]

arr = np.array(lst)
print(arr)

# ==

arr = np.linspace(1,12,12,dtype=int).reshape(2,2,3)
print(arr)


print("arr.shape:", arr.shape)  #모양(행열)
print("arr.ndim:", arr.ndim)  #차원수 == 3차원
print("arr.size:", arr.size)  #내부요소개수

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
arr.shape: (2, 2, 3)
arr.ndim: 3
arr.size: 12


In [35]:
print("arr[0, 0, 1]:\n", arr[0, 0, 1])
print("arr[1, 1, 1]:\n", arr[1, 1, 1])
print("arr[1, 1, 1:]:\n", arr[1, 1, 1:])
print("arr[1, :, 1:]:\n", arr[1, :, 1:])
print("arr[:, :, 1:]:\n", arr[:, :, 1:])

arr[0, 0, 1]:
 2
arr[1, 1, 1]:
 11
arr[1, 1, 1:]:
 [11 12]
arr[1, :, 1:]:
 [[ 8  9]
 [11 12]]
arr[:, :, 1:]:
 [[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


### boolean을 이용한 fancy indexing
- 조건식 결과가 `True`인 원소만 선택함
- 데이터 필터링의 기본 방식임
- Pandas 조건 필터링과 연결되는 개념임


In [40]:
arr = np.array([1,2,3,4,5])
print("arr[[1,3]]:", arr[[1,3]])
print(arr[[False, True, False, True, False]])
print("arr%2:", arr % 2)
print("arr%2==0:", arr % 2==0)
print("arr[arr%2==0]:", arr[arr%2==0])

arr[[1,3]]: [2 4]
[2 4]
arr%2: [1 0 1 0 1]
arr%2==0: [False  True False  True False]
arr[arr%2==0]: [2 4]


In [41]:
print(arr[arr>2])

[3 4 5]
