# 병합/분리
- 배열을 합치거나 나누는 기능 정리임
- shape 조건 확인이 중요함


In [1]:
import numpy as np

## 요소 삽입/삭제
- `np.insert()`: 지정 위치에 값 삽입함
- `np.delete()`: 지정 위치의 값 삭제함
- 원본 배열을 직접 바꾸지 않고 새 배열 반환함


In [10]:
# np.insert(ndarray, index, elems, axis)
# - 지정된 elements를 삽입한 새 배열이 반환 == 원본 유지
arr = np.arange(1,13).reshape(3,4)
arr

# axis = 0 단위 삽입(insert)
# == 행 삽입
# - 삽입할 행의 열 개수는 삽입 대상 ndarray의 열 개수와 일치해야 한다.
print(np.insert(arr, 1, [50,50,50,50], axis=0))
print(np.insert(arr, 1, [70], axis=0))  # 브로드캐스팅으로 인해 [70]이 [70 70 70 70]으로 확장변환된다.

print(np.insert(arr, 1, 90, axis=0))  # []를 안씌우고 0차원으로 해도 브로드캐스팅으로 확장된다.

[[ 1  2  3  4]
 [50 50 50 50]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [70 70 70 70]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [90 90 90 90]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
#arr
#axis = 1 == 열 방향 삽입
print(np.insert(arr, 2, [50,50,50], axis=1))
print(np.insert(arr, 2, [70], axis=1))
print(np.insert(arr, 2, 90, axis=1))

# axis=None은 1차원으로 변형 후 지정된 인덱스에 특정값 삽입
print(np.delete(arr, 0, 100, axis=None))


[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]
[[ 1  2 70  3  4]
 [ 5  6 70  7  8]
 [ 9 10 70 11 12]]
[[ 1  2 90  3  4]
 [ 5  6 90  7  8]
 [ 9 10 90 11 12]]


In [19]:
# delete(ndarray, index, axis)
# - 원본을 직접 삭제 X (원본 유지)
# - 삭제 결과가 적용된 새로운 배열 반환
arr
print(np.delete(arr, 0, axis=0)) #0번행 지우기
print(np.delete(arr, 0, axis=1)) #0번열 지우기

# axis=None은 1차원으로 변형 후 지정된 인덱스에 특정값 삭제
print(np.delete(arr, 0, axis=None)) #행렬을 전부 1차원으로 펼친 다음 0번인덱스 지우기
print(np.delete(arr, 0, axis=0))

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
[ 2  3  4  5  6  7  8  9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]


## 병합
- `np.append()`: 배열 뒤에 값 또는 배열 추가함 (prepend가 배열 앞에 값 추가하는 것)
- `np.vstack()`: 세로 방향 병합함 (버티컬)
- `np.hstack()`: 가로 방향 병합함 (호라이즌)
- `np.concatenate()`: 지정 axis 기준 병합함 (vstack, hstack 둘다 가능)
- `np.column_stack()`: 배열을 열 기준으로 결합함


In [22]:
# 병합함수는 shape 조건이 맞아야만 수행 가능
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### np.append()
- 배열 뒤에 값을 추가함
- `axis=None`이면 1차원으로 펼쳐 붙임
- `axis=0/1` 지정 시 shape 조건 필요함


In [26]:
print("np.append(arr1, arr2, axis=0 or 1 or None)")
print(np.append(arr1, arr2, axis=0)) #행방향으로 붙이기
print(np.append(arr1, arr2, axis=1)) #열방향으로 붙이기
print(np.append(arr1, arr2, axis=None)) #전체 1차원으로 풀고 붙이기

np.append(arr1, arr2, axis=0 or 1 or None)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### np.vstack()
- vertical stack의 약자임
- 세로 방향으로 쌓음
- `axis=0` 방향 병합과 유사함
- 열 개수가 같아야 함


In [29]:
np.vstack((arr1, arr2))  #튜플형태로 값 넣어야 함

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### np.hstack()
- horizontal stack의 약자임
- 가로 방향으로 붙임
- `axis=1` 방향 병합과 유사함
- 행 개수가 같아야 함


In [31]:
np.hstack((arr2, arr1))

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

### np.concatenate()
- 가장 일반적인 배열 연결 함수임
- `axis=0`: 아래로 붙임
- `axis=1`: 옆으로 붙임
- `axis=None`: 1차원으로 펼쳐 붙임


In [37]:
print(np.concatenate((arr1, arr2), axis=0))
print(np.concatenate((arr1, arr2), axis=1))
print(np.concatenate((arr1, arr2), axis=None))

# print를 구문 앞에 각각 붙여주면 모두 출력되고, 안붙이면 마지막 행만 실행출력됨

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### np.column_stack()
- 1차원 배열을 열로 세워 결합함
- 여러 feature를 표 형태로 묶을 때 유용함


In [38]:
# np.column_stack(tuple)
# - 1차원 배열들을 열로 묶어서 2차원 배열처럼 만들어줌
a = np.array([1,2,3])  # (3,)
b = np.array([4,5,6]) # (3,)

np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## 분할
- `np.vsplit()`: 세로 방향 분할함
- `np.hsplit()`: 가로 방향 분할함
- 나누는 개수가 행/열 개수와 맞아야 함


In [40]:
arr = np.arange(1,25).reshape(6,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

### np.vsplit()
- vertical split의 약자임
- 행 기준으로 배열을 나눔
- 행 개수가 나누는 개수로 정확히 나뉘어야 함


In [47]:
# 분할할 수는 행 방향 == 행의 약수(6,3,2,1)
# 분할할 수는 열 방향 == 열의 약수(4,2,1)

print("np.vsplit(arr, 6)")
print(np.vsplit(arr, 6)) #세로 6등분
print(np.vsplit(arr, 3)) #세로 3등분
print(np.vsplit(arr, 2)) #세로 2등분
# print(np.vsplit(arr, 4)) #세로 4등분 (ValueError: array split does not result in an equal division) 균등하게 나눌수없다.

np.vsplit(arr, 6)
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]]), array([[17, 18, 19, 20]]), array([[21, 22, 23, 24]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]


### np.hsplit()
- horizontal split의 약자임
- 열 기준으로 배열을 나눔
- 열 개수가 나누는 개수로 정확히 나뉘어야 함


In [48]:
print(np.hsplit(arr, 4))
print(np.hsplit(arr, 2))

[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]]), array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
